version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 0000
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" 
      - "28080:28080"
    depends_on: 
      - back
      - front
    
  web:
      image: front:latest
        depends_on: 
          - db
          - back
        ports: 
          - "4200:4200"
          - "28080:28080"
  back:
    image: backend:latest
    depends_on: 
      - db
      - front
    ports: 
      -"28080:28080"
volumes: 
  - db-data: