version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 0000
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5435:5432" 
      - "28084:28080"
    depends_on: 
      - back
      
    
  web:
      image: front:latest
      depends_on: 
        
        - back
      ports: 
        - "4200:4200"
        - "28082:28080"
  back:
    image: servicebackend:latest
    ports: 
      - "28083:28080"
volumes: 
  db-data: {}
